Repository JSJ-Organization/RNA_GIS, pull requests merged in 2024-07, with the labels that each got.

#11 Feature/be open api vworld search
  backend/build.gradle
  backend/src/main/java/com/jsj/backend/BackendApplication.java
  backend/src/main/java/com/jsj/backend/search/SearchController.java
  backend/src/main/java/com/jsj/backend/search/SearchService.java
  backend/src/main/java/com/jsj/backend/search/vworld/SpatialReferenceSystem.java
  backend/src/main/java/com/jsj/backend/search/vworld/VWorldLog.java
  backend/src/main/java/com/jsj/backend/search/vworld/VWorldLogRepository.java
  backend/src/main/java/com/jsj/backend/search/vworld/VWorldSearchApiClient.java
  backend/src/main/java/com/jsj/backend/search/vworld/VWorldSearchApiRequest.java
  backend/src/main/java/com/jsj/backend/search/vworld/VWorldSearchApiResponse.java
  docker-compose.yml
Labels: feature, dependencies

#12 #7 - vworld 검색 api ResponseDTO 건물명,건물상세명 필드 추가
  backend/src/main/java/com/jsj/backend/search/vworld/VWorldSearchApiResponse.java
Labels: feature

#13 #8 - Input 검색 기능 개선
  frontend/src/assets/scss/section/_input.scss
  frontend/src/components/Input.jsx
Labels: feature

#14 Feature/be integrate open api
  backend/.gitignore
  backend/Dockerfile
  backend/build.gradle
  backend/src/main/java/com/jsj/backend/search/SearchService.java
  docker-compose.yml
Labels: feature, dependencies

#15 Feature/fe create input function
  frontend/src/assets/scss/section/_input.scss
  frontend/src/components/Input.jsx
Labels: feature

#18 Feature/fe create map screen
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/scss/section/_map.scss
  frontend/src/assets/scss/style.scss
  frontend/src/components/Input.jsx
  frontend/src/components/Map.jsx
  frontend/src/views/MapView.jsx
Labels: feature, dependencies

#19 Feature/be open api farm construction rent info
  backend/src/main/java/com/jsj/backend/search/SearchController.java
  backend/src/main/java/com/jsj/backend/search/SearchService.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfo.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoApiClient.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoApiRequest.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoApiResponse.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoMapper.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoRepository.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoResponse.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoService.java
Labels: feature

#21 #20 - 매개변수에 name 속성 지정
  backend/src/main/java/com/jsj/backend/search/SearchController.java
Labels: fixed

#22 #20 - spring Batch Job 구현
  backend/build.gradle
  backend/src/main/java/com/jsj/backend/batch/FrcnRentInfoBatchConfig.java
  backend/src/main/java/com/jsj/backend/batch/FrcnRentInfoWriter.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfo.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoService.java
  backend/src/main/java/com/jsj/backend/util/DateUtil.java
Labels: feature, dependencies

#23 #7 - spring scheduler 구현
  backend/src/main/java/com/jsj/backend/batch/DemoController.java
  backend/src/main/java/com/jsj/backend/config/SchedulerConfig.java
  backend/src/main/java/com/jsj/backend/scheduler/FrcnRentInfoScheduler.java
Labels: feature

#25 Feature/be-create-map-function
  docker-compose.yml
Labels: dependencies

#26 Feature/be integrate open api
  backend/batch.sql
  backend/frcn.sql
  backend/src/main/java/com/jsj/backend/batch/FrcnRentInfoBatchConfig.java
  backend/src/main/java/com/jsj/backend/config/RestClientConfig.java
  backend/src/main/java/com/jsj/backend/search/SearchController.java
  backend/src/main/java/com/jsj/backend/search/SearchMapper.java
  backend/src/main/java/com/jsj/backend/search/SearchResponse.java
  backend/src/main/java/com/jsj/backend/search/SearchService.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfo.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoLog.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoLogRepository.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoMapper.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoRepository.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoResponse.java
  backend/src/main/java/com/jsj/backend/search/frcnRentInfo/FrcnRentInfoService.java
  backend/src/main/java/com/jsj/backend/search/juso/JusoApiClient.java
  backend/src/main/java/com/jsj/backend/search/juso/JusoApiRequest.java
  backend/src/main/java/com/jsj/backend/search/juso/JusoApiResponse.java
  backend/src/main/java/com/jsj/backend/search/vworld/VWorldSearchMapper.java
  backend/src/main/java/com/jsj/backend/search/vworld/VWorldSearchResponse.java
  backend/src/main/java/com/jsj/backend/search/vworld/VWorldSearchService.java
Labels: feature

#27 #7 - 백엔드 파일 구조 수정
  backend/src/main/java/com/jsj/backend/batch/FrcnRentInfoBatchConfig.java
  backend/src/main/java/com/jsj/backend/batch/FrcnRentInfoWriter.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfo.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoApiClient.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoApiRequest.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoApiResponse.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoLog.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoLogRepository.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoMapper.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoRepository.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoResponse.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoService.java
  backend/src/main/java/com/jsj/backend/search/SearchMapper.java
  backend/src/main/java/com/jsj/backend/search/SearchResponse.java
  backend/src/main/java/com/jsj/backend/search/SearchService.java
  backend/src/main/java/com/jsj/backend/vworld/SpatialReferenceSystem.java
  backend/src/main/java/com/jsj/backend/vworld/VWorldLog.java
  backend/src/main/java/com/jsj/backend/vworld/VWorldLogRepository.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchApiClient.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchApiRequest.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchApiResponse.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchMapper.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchResponse.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchService.java
Labels: refactor

#29 #7 - vworld wmts api 로직
  backend/src/main/java/com/jsj/backend/batch/FrcnRentInfoBatchConfig.java
  backend/src/main/java/com/jsj/backend/config/RestClientConfig.java
  backend/src/main/java/com/jsj/backend/search/SearchController.java
  backend/src/main/java/com/jsj/backend/search/SearchService.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/VWorldWMTSApiClient.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/VWorldWMTSApiRequest.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/VWorldWMTSMapper.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/VWorldWMTSService.java
Labels: feature

#30 Refactor/docker env set
  .gitignore
  backend/.gitignore
  backend/batch.sql
  backend/frcn.sql
  backend/src/main/resources/application.yml
  docker-compose.yml
  sql/batch.sql
  sql/frcn.sql
  sql/vworld.sql
Labels: refactor

#32 Feature/fe create map function 2
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/images/kr_map.png
  frontend/src/assets/images/logo.ico
  frontend/src/assets/scss/section/_input.scss
  frontend/src/assets/scss/section/_main.scss
  frontend/src/assets/scss/setting/_vars.scss
  frontend/src/components/Input.jsx
  frontend/src/components/Main.jsx
  frontend/src/components/PageMetadata.jsx
  frontend/src/hooks/useCssVariables.js
  frontend/src/layout/BasicLayout.jsx
  frontend/src/main.jsx
  frontend/src/views/HomeView.jsx
  frontend/src/views/InputView.jsx
  frontend/src/views/MapView.jsx
  frontend/src/views/agri/AgriInput.jsx
  frontend/src/views/agri/AgriMap.jsx
  frontend/src/views/coord/CoordInput.jsx
  frontend/src/views/coord/CoordMap.jsx
Labels: feature, refactor

#34 #33 - fe-be 컨테이너화
  backend/src/main/java/com/jsj/backend/config/WebConfig.java
  docker-compose.yml
  frontend/Dockerfile
  frontend/nginx/default.conf
  frontend/vite.config.js
Labels: feature

#36 Fix/docker disable
  backend/src/main/java/com/jsj/backend/config/WebConfig.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoMapper.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchMapper.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/VWorldWMTSApiClient.java
  docker-compose.yml
  frontend/Dockerfile
  frontend/src/components/Input.jsx
  frontend/src/components/Map.jsx
  frontend/vite.config.js
Labels: fixed

#37 Feature/fe create map function 3
  frontend/src/components/Input.jsx
  frontend/src/components/Modal.jsx
  frontend/src/components/PageMetadata.jsx
Labels: refactor

#40 Feature/fe argi mach function
  frontend/src/App.jsx
  frontend/src/PathContext.jsx
  frontend/src/assets/images/marker.png
  frontend/src/components/Input.jsx
  frontend/src/components/Map.jsx
  frontend/src/components/Modal.jsx
  frontend/src/components/PageMetadata.jsx
  frontend/src/pathData.js
  frontend/src/views/HomeView.jsx
  frontend/src/views/agri/AgriInput.jsx
  frontend/src/views/coord/CoordInput.jsx
Labels: feature, fixed, refactor

#41 Fix/be exception
  backend/src/main/java/com/jsj/backend/batch/frcnRentInfo/FrcnRentInfoBatchConfig.java
  backend/src/main/java/com/jsj/backend/batch/frcnRentInfo/FrcnRentInfoJobExecutionListener.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/dto/FrcnRentInfoMapper.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/entity/FrcnRentInfoRepository.java
  backend/src/main/java/com/jsj/backend/search/SearchService.java
  backend/src/main/java/com/jsj/backend/search/dto/SearchMapper.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchService.java
  backend/src/main/java/com/jsj/backend/vworld/search/dto/VWorldSearchMapper.java
Labels: fixed

#43 Feature/be swagger
  backend/build.gradle
  backend/src/main/java/com/jsj/backend/batch/frcnRentInfo/FrcnRentInfoJobExecutionListener.java
  backend/src/main/java/com/jsj/backend/config/SwaggerConfig.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoController.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoService.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/dto/FrcnRentInfoMapper.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/dto/FrcnRentInfoResponse.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/httpClient/FrcnRentInfoApiClient.java
  backend/src/main/java/com/jsj/backend/scheduler/FrcnRentInfoScheduler.java
  backend/src/main/java/com/jsj/backend/search/SearchController.java
  backend/src/main/java/com/jsj/backend/search/SearchService.java
  backend/src/main/java/com/jsj/backend/search/dto/SearchMapper.java
  backend/src/main/java/com/jsj/backend/search/dto/SearchResponse.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchController.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchService.java
  backend/src/main/java/com/jsj/backend/vworld/search/dto/VWorldSearchMapper.java
  backend/src/main/java/com/jsj/backend/vworld/search/dto/VWorldSearchResponse.java
  backend/src/main/java/com/jsj/backend/vworld/search/httpClient/VWorldSearchApiClient.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/VWorldWMTSController.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/VWorldWMTSService.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/dto/VWorldWMTSApiRequest.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/dto/VWorldWMTSMapper.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/httpClient/VWorldWMTSApiClient.java
  backend/src/main/resources/application.yml
Labels: documentation, feature, dependencies

#44 #7 - 주소 키워드로 농기계임대정보 검색
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoController.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoService.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/entity/FrcnRentInfoRepository.java
  backend/src/main/java/com/jsj/backend/search/SearchService.java
Labels: feature

#45 #7 - 농기계임대정보 검색 시 id 반환
  backend/src/main/java/com/jsj/backend/frcnRentInfo/dto/FrcnRentInfoMapper.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/dto/FrcnRentInfoResponse.java
Labels: feature

#46 Feature/be log
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoService.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/log/FrcnRentInfoLog.java
  backend/src/main/java/com/jsj/backend/vworld/log/VWorldLog.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchService.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/VWorldWMTSService.java
Labels: feature

#48 #47 - 전국농기계임대정보 조회 조건 변경
  backend/src/main/java/com/jsj/backend/batch/frcnRentInfo/FrcnRentInfoBatchConfig.java
  backend/src/main/java/com/jsj/backend/batch/frcnRentInfo/FrcnRentInfoBatchService.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoApiService.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/FrcnRentInfoService.java
  backend/src/main/java/com/jsj/backend/frcnRentInfo/entity/FrcnRentInfoRepository.java
  backend/src/main/java/com/jsj/backend/search/SearchService.java
  backend/src/main/java/com/jsj/backend/util/CleanInputUtil.java
  backend/src/main/java/com/jsj/backend/util/ValidationUtil.java
Labels: fixed

#49 #31 - VWorld api 서비스 구조 리팩토링
  backend/src/main/java/com/jsj/backend/util/ValidationUtil.java
  backend/src/main/java/com/jsj/backend/vworld/search/VWorldSearchService.java
  backend/src/main/java/com/jsj/backend/vworld/wmts/VWorldWMTSService.java
Labels: refactor

#50 Feature/fe create argi function
  frontend/src/App.jsx
  frontend/src/assets/scss/section/_input.scss
  frontend/src/assets/scss/section/_main.scss
  frontend/src/components/Input.jsx
  frontend/src/components/Loader.jsx
  frontend/src/components/PageMetadata.jsx
  frontend/src/components/map/AgriMap.jsx
  frontend/src/components/map/CoordMap.jsx
  frontend/src/components/modal/AgriModal.jsx
  frontend/src/components/modal/CoordModal.jsx
  frontend/src/contexts/LoadingContext.jsx
  frontend/src/contexts/PathContext.jsx
  frontend/src/pathData.js
  frontend/src/views/agri/AgriMap.jsx
  frontend/src/views/coord/CoordMap.jsx
  frontend/src/views/input/AgriInputView.jsx
  frontend/src/views/input/CoordInputView.jsx
  frontend/src/views/map/AgriMapView.jsx
  frontend/src/views/map/CoordMapView.jsx
Labels: feature, refactor

#52 #51 - ci/cd 스크립트 작성
  .github/workflows/deploy.yml
  docker-compose.yml
  frontend/Dockerfile
  frontend/nginx/default.conf
Labels: ci/cd

#53 #51 - ci/cd 스크립트 포트 수정
  .github/workflows/deploy.yml
Labels: ci/cd

#54 #51 - ci/cd 스크립트 포트 수정, 옵션 수정
  .github/workflows/deploy.yml
Labels: ci/cd

#55 #51 - ci/cd github actions 누락된 환경변수 추가
  .github/workflows/deploy.yml
Labels: ci/cd

#56 #51 - ssh 가상 터미널 할당
  .github/workflows/deploy.yml
Labels: ci/cd

#57 ci/cd
  .github/workflows/deploy.yml
  .gitignore
  backend/Dockerfile
  docker-compose.yml
  frontend/Dockerfile
  frontend/docker-entrypoint.sh
  frontend/nginx/default.conf
  frontend/nginx/default.conf.template
  frontend/nginx/nginx.conf
Labels: ci/cd

#58 #51 - prod-env DOMAIN CORS 적용
  backend/src/main/java/com/jsj/backend/config/WebConfig.java
  backend/src/main/resources/application.yml
  docker-compose.yml
Labels: fixed

#59 #51 - prod-env localhost를 VITE_DOMAIN로 대체
  .github/workflows/deploy.yml
  docker-compose.yml
  frontend/Dockerfile
  frontend/src/components/map/AgriMap.jsx
  frontend/src/components/map/CoordMap.jsx
  frontend/src/pathData.js
Labels: fixed, refactor

#63 #51 - ssl 볼륨 해제
  docker-compose.yml
Labels: ci/cd

#64 Documentation/readme
  README.md
Labels: documentation
